/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as LeagueRouteImport } from './routes/league'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TrainingsRouteImport } from './routes/trainings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MatchNewRouteImport } from './routes/match.new'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as LiveShareTokenRouteImport } from './routes/live.$shareToken'
import { Route as PlayerPlayerIdRouteImport } from './routes/player.$playerId'
import { Route as ReportMatchIdRouteImport } from './routes/report.$matchId'
import { Route as TrainingNewRouteImport } from './routes/training.new'
import { Route as TrainingSessionIdRouteImport } from './routes/training.$sessionId'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as StatsFriendlyRouteImport } from './routes/stats.friendly'
import { Route as StatsHistoryRouteImport } from './routes/stats.history'
import { Route as StatsOfficialRouteImport } from './routes/stats.official'
import { Route as StatsTrainingRouteImport } from './routes/stats.training'
import { Route as StatsIndexRouteImport } from './routes/stats.index'
import { Route as StatsTeamTeamIdRouteImport } from './routes/stats.team.$teamId'
import { Route as StatsCompareRouteImport } from './routes/stats.compare'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueRoute = LeagueRouteImport.update({
  id: '/league',
  path: '/league',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingsRoute = TrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchNewRoute = MatchNewRouteImport.update({
  id: '/match/new',
  path: '/match/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveShareTokenRoute = LiveShareTokenRouteImport.update({
  id: '/live/$shareToken',
  path: '/live/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerPlayerIdRoute = PlayerPlayerIdRouteImport.update({
  id: '/player/$playerId',
  path: '/player/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportMatchIdRoute = ReportMatchIdRouteImport.update({
  id: '/report/$matchId',
  path: '/report/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingNewRoute = TrainingNewRouteImport.update({
  id: '/training/new',
  path: '/training/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingSessionIdRoute = TrainingSessionIdRouteImport.update({
  id: '/training/$sessionId',
  path: '/training/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/',
  getParentRoute: () => StatsRoute,
} as any)
const StatsFriendlyRoute = StatsFriendlyRouteImport.update({
  id: '/stats/friendly',
  path: '/friendly',
  getParentRoute: () => StatsRoute,
} as any)
const StatsHistoryRoute = StatsHistoryRouteImport.update({
  id: '/stats/history',
  path: '/history',
  getParentRoute: () => StatsRoute,
} as any)
const StatsOfficialRoute = StatsOfficialRouteImport.update({
  id: '/stats/official',
  path: '/official',
  getParentRoute: () => StatsRoute,
} as any)
const StatsTrainingRoute = StatsTrainingRouteImport.update({
  id: '/stats/training',
  path: '/training',
  getParentRoute: () => StatsRoute,
} as any)
const StatsTeamTeamIdRoute = StatsTeamTeamIdRouteImport.update({
  id: '/stats/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => StatsRoute,
} as any)
const StatsCompareRoute = StatsCompareRouteImport.update({
  id: '/stats/compare',
  path: '/compare',
  getParentRoute: () => StatsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/league': typeof LeagueRoute
  '/roster': typeof RosterRoute
  '/matches': typeof MatchesRoute
  '/teams': typeof TeamsRoute
  '/trainings': typeof TrainingsRoute
  '/settings': typeof SettingsRoute
  '/match/new': typeof MatchNewRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/live/$shareToken': typeof LiveShareTokenRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/report/$matchId': typeof ReportMatchIdRoute
  '/training/new': typeof TrainingNewRoute
  '/training/$sessionId': typeof TrainingSessionIdRoute
  '/stats': typeof StatsRouteWithChildren
  '/stats/': typeof StatsIndexRoute
  '/stats/friendly': typeof StatsFriendlyRoute
  '/stats/history': typeof StatsHistoryRoute
  '/stats/official': typeof StatsOfficialRoute
  '/stats/training': typeof StatsTrainingRoute
  '/stats/team/$teamId': typeof StatsTeamTeamIdRoute
  '/stats/compare': typeof StatsCompareRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/league': typeof LeagueRoute
  '/roster': typeof RosterRoute
  '/matches': typeof MatchesRoute
  '/teams': typeof TeamsRoute
  '/trainings': typeof TrainingsRoute
  '/settings': typeof SettingsRoute
  '/match/new': typeof MatchNewRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/live/$shareToken': typeof LiveShareTokenRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/report/$matchId': typeof ReportMatchIdRoute
  '/training/new': typeof TrainingNewRoute
  '/training/$sessionId': typeof TrainingSessionIdRoute
  '/stats': typeof StatsIndexRoute
  '/stats/friendly': typeof StatsFriendlyRoute
  '/stats/history': typeof StatsHistoryRoute
  '/stats/official': typeof StatsOfficialRoute
  '/stats/training': typeof StatsTrainingRoute
  '/stats/team/$teamId': typeof StatsTeamTeamIdRoute
  '/stats/compare': typeof StatsCompareRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AdminRoute
  '/calendar': typeof CalendarRoute
  '/league': typeof LeagueRoute
  '/roster': typeof RosterRoute
  '/matches': typeof MatchesRoute
  '/teams': typeof TeamsRoute
  '/trainings': typeof TrainingsRoute
  '/settings': typeof SettingsRoute
  '/match/new': typeof MatchNewRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/live/$shareToken': typeof LiveShareTokenRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/report/$matchId': typeof ReportMatchIdRoute
  '/training/new': typeof TrainingNewRoute
  '/training/$sessionId': typeof TrainingSessionIdRoute
  '/stats': typeof StatsRouteWithChildren
  '/stats/': typeof StatsIndexRoute
  '/stats/friendly': typeof StatsFriendlyRoute
  '/stats/history': typeof StatsHistoryRoute
  '/stats/official': typeof StatsOfficialRoute
  '/stats/training': typeof StatsTrainingRoute
  '/stats/team/$teamId': typeof StatsTeamTeamIdRoute
  '/stats/compare': typeof StatsCompareRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/calendar'
    | '/league'
    | '/roster'
    | '/matches'
    | '/teams'
    | '/trainings'
    | '/settings'
    | '/match/new'
    | '/match/$matchId'
    | '/live/$shareToken'
    | '/player/$playerId'
    | '/report/$matchId'
    | '/training/new'
    | '/training/$sessionId'
    | '/stats'
    | '/stats/'
    | '/stats/friendly'
    | '/stats/history'
    | '/stats/official'
    | '/stats/training'
    | '/stats/team/$teamId'
    | '/stats/compare'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/calendar'
    | '/league'
    | '/roster'
    | '/matches'
    | '/teams'
    | '/trainings'
    | '/settings'
    | '/match/new'
    | '/match/$matchId'
    | '/live/$shareToken'
    | '/player/$playerId'
    | '/report/$matchId'
    | '/training/new'
    | '/training/$sessionId'
    | '/stats'
    | '/stats/friendly'
    | '/stats/history'
    | '/stats/official'
    | '/stats/training'
    | '/stats/team/$teamId'
    | '/stats/compare'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin'
    | '/calendar'
    | '/league'
    | '/roster'
    | '/matches'
    | '/teams'
    | '/trainings'
    | '/settings'
    | '/match/new'
    | '/match/$matchId'
    | '/live/$shareToken'
    | '/player/$playerId'
    | '/report/$matchId'
    | '/training/new'
    | '/training/$sessionId'
    | '/stats'
    | '/stats/'
    | '/stats/friendly'
    | '/stats/history'
    | '/stats/official'
    | '/stats/training'
    | '/stats/team/$teamId'
    | '/stats/compare'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AdminRoute: typeof AdminRoute
  CalendarRoute: typeof CalendarRoute
  LeagueRoute: typeof LeagueRoute
  RosterRoute: typeof RosterRoute
  MatchesRoute: typeof MatchesRoute
  TeamsRoute: typeof TeamsRoute
  TrainingsRoute: typeof TrainingsRoute
  SettingsRoute: typeof SettingsRoute
  MatchNewRoute: typeof MatchNewRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  LiveShareTokenRoute: typeof LiveShareTokenRoute
  PlayerPlayerIdRoute: typeof PlayerPlayerIdRoute
  ReportMatchIdRoute: typeof ReportMatchIdRoute
  TrainingNewRoute: typeof TrainingNewRoute
  TrainingSessionIdRoute: typeof TrainingSessionIdRoute
  StatsRoute: typeof StatsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league': {
      id: '/league'
      path: '/league'
      fullPath: '/league'
      preLoaderRoute: typeof LeagueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainings': {
      id: '/trainings'
      path: '/trainings'
      fullPath: '/trainings'
      preLoaderRoute: typeof TrainingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/new': {
      id: '/match/new'
      path: '/match/new'
      fullPath: '/match/new'
      preLoaderRoute: typeof MatchNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$shareToken': {
      id: '/live/$shareToken'
      path: '/live/$shareToken'
      fullPath: '/live/$shareToken'
      preLoaderRoute: typeof LiveShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$playerId': {
      id: '/player/$playerId'
      path: '/player/$playerId'
      fullPath: '/player/$playerId'
      preLoaderRoute: typeof PlayerPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$matchId': {
      id: '/report/$matchId'
      path: '/report/$matchId'
      fullPath: '/report/$matchId'
      preLoaderRoute: typeof ReportMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/new': {
      id: '/training/new'
      path: '/training/new'
      fullPath: '/training/new'
      preLoaderRoute: typeof TrainingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/$sessionId': {
      id: '/training/$sessionId'
      path: '/training/$sessionId'
      fullPath: '/training/$sessionId'
      preLoaderRoute: typeof TrainingSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof StatsRoute
    }
    '/stats/friendly': {
      id: '/stats/friendly'
      path: '/friendly'
      fullPath: '/stats/friendly'
      preLoaderRoute: typeof StatsFriendlyRouteImport
      parentRoute: typeof StatsRoute
    }
    '/stats/history': {
      id: '/stats/history'
      path: '/history'
      fullPath: '/stats/history'
      preLoaderRoute: typeof StatsHistoryRouteImport
      parentRoute: typeof StatsRoute
    }
    '/stats/official': {
      id: '/stats/official'
      path: '/official'
      fullPath: '/stats/official'
      preLoaderRoute: typeof StatsOfficialRouteImport
      parentRoute: typeof StatsRoute
    }
    '/stats/training': {
      id: '/stats/training'
      path: '/training'
      fullPath: '/stats/training'
      preLoaderRoute: typeof StatsTrainingRouteImport
      parentRoute: typeof StatsRoute
    }
    '/stats/team/$teamId': {
      id: '/stats/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/stats/team/$teamId'
      preLoaderRoute: typeof StatsTeamTeamIdRouteImport
      parentRoute: typeof StatsRoute
    }
    '/stats/compare': {
      id: '/stats/compare'
      path: '/compare'
      fullPath: '/stats/compare'
      preLoaderRoute: typeof StatsCompareRouteImport
      parentRoute: typeof StatsRoute
    }
  }
}

interface StatsRouteChildren {
  StatsFriendlyRoute: typeof StatsFriendlyRoute
  StatsHistoryRoute: typeof StatsHistoryRoute
  StatsOfficialRoute: typeof StatsOfficialRoute
  StatsTrainingRoute: typeof StatsTrainingRoute
  StatsIndexRoute: typeof StatsIndexRoute
  StatsTeamTeamIdRoute: typeof StatsTeamTeamIdRoute
  StatsCompareRoute: typeof StatsCompareRoute
}

const StatsRouteChildren: StatsRouteChildren = {
  StatsFriendlyRoute: StatsFriendlyRoute,
  StatsHistoryRoute: StatsHistoryRoute,
  StatsOfficialRoute: StatsOfficialRoute,
  StatsTrainingRoute: StatsTrainingRoute,
  StatsIndexRoute: StatsIndexRoute,
  StatsTeamTeamIdRoute: StatsTeamTeamIdRoute,
  StatsCompareRoute: StatsCompareRoute,
}

const StatsRouteWithChildren = StatsRoute._addFileChildren(StatsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminRoute: AdminRoute,
  CalendarRoute: CalendarRoute,
  LeagueRoute: LeagueRoute,
  RosterRoute: RosterRoute,
  MatchesRoute: MatchesRoute,
  TeamsRoute: TeamsRoute,
  TrainingsRoute: TrainingsRoute,
  SettingsRoute: SettingsRoute,
  MatchNewRoute: MatchNewRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  LiveShareTokenRoute: LiveShareTokenRoute,
  PlayerPlayerIdRoute: PlayerPlayerIdRoute,
  ReportMatchIdRoute: ReportMatchIdRoute,
  TrainingNewRoute: TrainingNewRoute,
  TrainingSessionIdRoute: TrainingSessionIdRoute,
  StatsRoute: StatsRouteWithChildren,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
