/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingsRouteImport } from './routes/trainings'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatsIndexRouteImport } from './routes/stats.index'
import { Route as TrainingNewRouteImport } from './routes/training.new'
import { Route as TrainingSessionIdRouteImport } from './routes/training.$sessionId'
import { Route as StatsTrainingRouteImport } from './routes/stats.training'
import { Route as StatsOfficialRouteImport } from './routes/stats.official'
import { Route as StatsHistoryRouteImport } from './routes/stats.history'
import { Route as StatsFriendlyRouteImport } from './routes/stats.friendly'
import { Route as ReportMatchIdRouteImport } from './routes/report.$matchId'
import { Route as PlayerPlayerIdRouteImport } from './routes/player.$playerId'
import { Route as MatchNewRouteImport } from './routes/match.new'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsTeamTeamIdRouteImport } from './routes/stats.team.$teamId'

const TrainingsRoute = TrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsTeamTeamIdRoute = StatsTeamTeamIdRouteImport.update({
  id: '/stats/team/$teamId',
  path: '/team/$teamId',
  getParentRoute: () => StatsRoute,
} as any)

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StatsRoute,
} as any)
const TrainingNewRoute = TrainingNewRouteImport.update({
  id: '/training/new',
  path: '/training/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingSessionIdRoute = TrainingSessionIdRouteImport.update({
  id: '/training/$sessionId',
  path: '/training/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsTrainingRoute = StatsTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => StatsRoute,
} as any)
const StatsOfficialRoute = StatsOfficialRouteImport.update({
  id: '/official',
  path: '/official',
  getParentRoute: () => StatsRoute,
} as any)
const StatsHistoryRoute = StatsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => StatsRoute,
} as any)
const StatsFriendlyRoute = StatsFriendlyRouteImport.update({
  id: '/friendly',
  path: '/friendly',
  getParentRoute: () => StatsRoute,
} as any)
const ReportMatchIdRoute = ReportMatchIdRouteImport.update({
  id: '/report/$matchId',
  path: '/report/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerPlayerIdRoute = PlayerPlayerIdRouteImport.update({
  id: '/player/$playerId',
  path: '/player/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchNewRoute = MatchNewRouteImport.update({
  id: '/match/new',
  path: '/match/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/stats': typeof StatsRouteWithChildren
  '/teams': typeof TeamsRoute
  '/trainings': typeof TrainingsRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/match/new': typeof MatchNewRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/report/$matchId': typeof ReportMatchIdRoute
  '/stats/friendly': typeof StatsFriendlyRoute
  '/stats/history': typeof StatsHistoryRoute
  '/stats/official': typeof StatsOfficialRoute
  '/stats/training': typeof StatsTrainingRoute
  '/training/$sessionId': typeof TrainingSessionIdRoute
  '/training/new': typeof TrainingNewRoute
  '/stats/': typeof StatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/teams': typeof TeamsRoute
  '/trainings': typeof TrainingsRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/match/new': typeof MatchNewRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/report/$matchId': typeof ReportMatchIdRoute
  '/stats/friendly': typeof StatsFriendlyRoute
  '/stats/history': typeof StatsHistoryRoute
  '/stats/official': typeof StatsOfficialRoute
  '/stats/training': typeof StatsTrainingRoute
  '/training/$sessionId': typeof TrainingSessionIdRoute
  '/training/new': typeof TrainingNewRoute
  '/stats': typeof StatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/matches': typeof MatchesRoute
  '/stats': typeof StatsRouteWithChildren
  '/teams': typeof TeamsRoute
  '/trainings': typeof TrainingsRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/match/new': typeof MatchNewRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/report/$matchId': typeof ReportMatchIdRoute
  '/stats/friendly': typeof StatsFriendlyRoute
  '/stats/history': typeof StatsHistoryRoute
  '/stats/official': typeof StatsOfficialRoute
  '/stats/training': typeof StatsTrainingRoute
  '/training/$sessionId': typeof TrainingSessionIdRoute
  '/training/new': typeof TrainingNewRoute
  '/stats/': typeof StatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/matches'
    | '/stats'
    | '/teams'
    | '/trainings'
    | '/match/$matchId'
    | '/match/new'
    | '/player/$playerId'
    | '/report/$matchId'
    | '/stats/friendly'
    | '/stats/history'
    | '/stats/official'
    | '/stats/training'
    | '/training/$sessionId'
    | '/training/new'
    | '/stats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/matches'
    | '/teams'
    | '/trainings'
    | '/match/$matchId'
    | '/match/new'
    | '/player/$playerId'
    | '/report/$matchId'
    | '/stats/friendly'
    | '/stats/history'
    | '/stats/official'
    | '/stats/training'
    | '/training/$sessionId'
    | '/training/new'
    | '/stats'
  id:
    | '__root__'
    | '/'
    | '/matches'
    | '/stats'
    | '/teams'
    | '/trainings'
    | '/match/$matchId'
    | '/match/new'
    | '/player/$playerId'
    | '/report/$matchId'
    | '/stats/friendly'
    | '/stats/history'
    | '/stats/official'
    | '/stats/training'
    | '/training/$sessionId'
    | '/training/new'
    | '/stats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatchesRoute: typeof MatchesRoute
  StatsRoute: typeof StatsRouteWithChildren
  TeamsRoute: typeof TeamsRoute
  TrainingsRoute: typeof TrainingsRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  MatchNewRoute: typeof MatchNewRoute
  PlayerPlayerIdRoute: typeof PlayerPlayerIdRoute
  ReportMatchIdRoute: typeof ReportMatchIdRoute
  TrainingSessionIdRoute: typeof TrainingSessionIdRoute
  TrainingNewRoute: typeof TrainingNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainings': {
      id: '/trainings'
      path: '/trainings'
      fullPath: '/trainings'
      preLoaderRoute: typeof TrainingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof StatsRoute
    }
    '/training/new': {
      id: '/training/new'
      path: '/training/new'
      fullPath: '/training/new'
      preLoaderRoute: typeof TrainingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/$sessionId': {
      id: '/training/$sessionId'
      path: '/training/$sessionId'
      fullPath: '/training/$sessionId'
      preLoaderRoute: typeof TrainingSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/training': {
      id: '/stats/training'
      path: '/training'
      fullPath: '/stats/training'
      preLoaderRoute: typeof StatsTrainingRouteImport
      parentRoute: typeof StatsRoute
    }
    '/stats/official': {
      id: '/stats/official'
      path: '/official'
      fullPath: '/stats/official'
      preLoaderRoute: typeof StatsOfficialRouteImport
      parentRoute: typeof StatsRoute
    }
    '/stats/history': {
      id: '/stats/history'
      path: '/history'
      fullPath: '/stats/history'
      preLoaderRoute: typeof StatsHistoryRouteImport
      parentRoute: typeof StatsRoute
    }
    '/stats/friendly': {
      id: '/stats/friendly'
      path: '/friendly'
      fullPath: '/stats/friendly'
      preLoaderRoute: typeof StatsFriendlyRouteImport
      parentRoute: typeof StatsRoute
    }
    '/report/$matchId': {
      id: '/report/$matchId'
      path: '/report/$matchId'
      fullPath: '/report/$matchId'
      preLoaderRoute: typeof ReportMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$playerId': {
      id: '/player/$playerId'
      path: '/player/$playerId'
      fullPath: '/player/$playerId'
      preLoaderRoute: typeof PlayerPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/new': {
      id: '/match/new'
      path: '/match/new'
      fullPath: '/match/new'
      preLoaderRoute: typeof MatchNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/team/$teamId': {
      id: '/stats/team/$teamId'
      path: '/team/$teamId'
      fullPath: '/stats/team/$teamId'
      preLoaderRoute: typeof StatsTeamTeamIdRouteImport
      parentRoute: typeof StatsRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StatsRouteChildren {
  StatsFriendlyRoute: typeof StatsFriendlyRoute
  StatsHistoryRoute: typeof StatsHistoryRoute
  StatsOfficialRoute: typeof StatsOfficialRoute
  StatsTrainingRoute: typeof StatsTrainingRoute
  StatsIndexRoute: typeof StatsIndexRoute
  StatsTeamTeamIdRoute: typeof StatsTeamTeamIdRoute
}

const StatsRouteChildren: StatsRouteChildren = {
  StatsFriendlyRoute: StatsFriendlyRoute,
  StatsHistoryRoute: StatsHistoryRoute,
  StatsOfficialRoute: StatsOfficialRoute,
  StatsTrainingRoute: StatsTrainingRoute,
  StatsIndexRoute: StatsIndexRoute,
  StatsTeamTeamIdRoute: StatsTeamTeamIdRoute,
}

const StatsRouteWithChildren = StatsRoute._addFileChildren(StatsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatchesRoute: MatchesRoute,
  StatsRoute: StatsRouteWithChildren,
  TeamsRoute: TeamsRoute,
  TrainingsRoute: TrainingsRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  MatchNewRoute: MatchNewRoute,
  PlayerPlayerIdRoute: PlayerPlayerIdRoute,
  ReportMatchIdRoute: ReportMatchIdRoute,
  TrainingSessionIdRoute: TrainingSessionIdRoute,
  TrainingNewRoute: TrainingNewRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
